### ISSUE TITLE
Documentation RE Uninstall

### ISSUE THREAD

**Issue by mosen** [MagerValp/LoginScriptPlugin#1]
Hiya Mager,
The README says to remove the bundle and then run the uninstall script, but if I attempt to remove the bundle and then run the script, the script will fail with a message like "LoginScriptBundle not found".

So I would say either adjust readme to only run the script if you want to uninstall, or adjust the script to remove the authorization db entries etc without LoginScriptBundle existing.

M.

**Comment by MagerValp** [comment]
Fixed, thanks.
