### ISSUE TITLE
Loginscript for AD users fails on first logon

### ISSUE THREAD

**Issue by calum-github** [MagerValp/LoginScriptPlugin#2]
Using a postmount-user-scriptname.sh
Machine is freshly deployed and bound to AD. 
Mobile user accounts are enabled
User logs in as AD user
LoginScriptPlugin reports:
Can't execute script, homedir lookup failed

Logout and log back in and script executes as expected.

Is this a case of needing to put some sleep time into the postmount-user-script.sh? Is the script running before the homedirectory value gets put into the users dscl record?
This does not appear to be an issue for local accounts

**Comment by jessepeterson** [comment]
This issue seems related to tburgin/FV2AuthPlugin#5. That is: the ordering of an authentication plugin is important and perhaps LoginScriptPlugin comes before the actual home directory for the user is created as a mobile account.

**Comment by MagerValp** [comment]
Thanks, this should be fixed now.
