### ISSUE TITLE
Use prevented by default permissions on OS X

### ISSUE THREAD

**Issue by jessepeterson** [MagerValp/LoginScriptPlugin#3]
LoginScriptPlugin [blocks](https://github.com/MagerValp/LoginScriptPlugin/blob/master/LoginScriptPlugin/LoginScriptPlugin.c#L294-L298) a script if the root volume is group writable and does not have a group of wheel. By default OS X is group writable and group assigned is _admin_. This means out of the box LoginScriptPlugin won't work on Yosemite. I guess the choices are:
1. It's a feature, not a bug. Do nothing and force folks to change their root volume permissions.
   - If this is true should at least be a note in the docs saying such.
2. In the installer `postinstall` script change the permissions on the root volume to allow out-of-the-box use.
3. The requirement for such strict permissions is relaxed a little for the root volume. Seems that non-root+wheel-writable on the parent directory (`/Library/Application Support/LoginScriptPlugin`) only could be forced.

**Comment by andreasley** [comment]
On my systems with OS X 10.10 and 10.11, the group is "wheel". On the ones with 10.8, it is "admin". It seems that Apple changed this for Mavericks or Yosemite. What version of OS X are you using, @jessepeterson ?

**Comment by MagerValp** [comment]
Thanks, I relaxed the check a bit and allow admin writable paths.
